Courses/Courses/urls.py
from django.conf.urls import url,include

urlpatterns = [
    url(r'^',include('apps.courses_app.urls', namespace = "course")),
]

Courses/apps/courses_app/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$',views.index),
    url(r'^course$',views.addCourse),
    url(r'^destroy/(?P<id>\d+)$', views.destroy, name = "destroy"),
    url(r'^confirmDestroy/(?P<id>\d+)$', views.confirmDestroy, name = 'confirm')
]

Courses/apps/courses_app/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Course(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

Courses/apps/courses_app/views.py
from django.shortcuts import render, redirect
from .models import Course

# Create your views here.
def index(request):
    courses = Course.objects.all()
    context = {
        "daniel": courses
    }
    return render(request,"courses_app/index.html", context)

def addCourse(request):
    Course.objects.create(name=request.POST['name'],description=request.POST['description'])
    return redirect('/')

def destroy(request, id):
    context = {
     "course":Course.objects.get(id=id)
    }
    return render(request, 'courses_app/destroy.html',context)

def confirmDestroy(request, id):
    deleteMe = Course.objects.get(id=id)
    deleteMe.delete()
    return redirect('/')

Courses/apps/courses_app/templates/courses_app/destroy.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Login/ Register</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </head>
  <body>
    <h1>Are you shure you want to delete the folowing course?</h1>
      <h4>Name:{{course.name}}</h4>
      <h4>Description:{{course.description}}</h4><br>
    <form action='/'>
        {% csrf_token %}
       <input type="submit" value ="No">
     </form>
     <form action="{% url 'course:confirm' id=course.id %}" method='post'>
       {% csrf_token %}
       <input type="submit" value ="Yes, I want to delete this">
     </form>
  </body>
</html>

Courses/apps/courses_app/templates/courses_app/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Courses</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <style media="screen">
    .tabel {
      width: 650px;
    }
    body {
      margin:30px;
    }
    </style>
  </head>
  <body>
    <h2>Add a new course</h2>
    <form action="/course" method="post">
      {% csrf_token %}
      Name: <input type="text" name="name" placeholder="Add a new course"><br>
      Description:<br>
      <textarea name="description" rows="8" cols="80"></textarea><br>
      <input type="submit" name="btn" value="Add Course">
    </form>

    <h2>Courses</h2>
  <div class="tabel">
    <table class="table table-striped">
      <tr>
        <th>Course Name</th>
        <th>Description</th>
        <th>Date Added</th>
        <th>Actions</th>
      </tr>
        {% for course in daniel %}
      <tr>
        <td>{{course.name}}</td>
        <td>{{course.description}}</td>
        <td>{{course.created_at}}</td>
        <td><a href="{% url 'course:destroy' id=course.id%}">remove</a></td>
      </tr>
        {% endfor %}
    </table>
  </div>
  </body>
</html>